### ISSUE TITLE
Implement pixel-based shelter destruction and collision

### ISSUE THREAD

**Issue by brunotnasc** [brunotnasc/space-invaders#6]
# Overview
Currently, the game uses a fixed sequence of ten different sprites (seen below) to represent the health of a shelter; also, damaging a shelter doesn't change its collision box. The objective here is to make it work as in the original game.

![Shelter full](https://user-images.githubusercontent.com/40273816/125182092-80385a00-e1e1-11eb-9cc6-66def6c31c8d.png) ![shelterDamaged_1](https://user-images.githubusercontent.com/40273816/125182093-80d0f080-e1e1-11eb-9bb1-c6dfe89f8724.png) ![shelterDamaged_2 copy](https://user-images.githubusercontent.com/40273816/125182094-81698700-e1e1-11eb-815a-f88f3c2da868.png) ![shelterDamaged_3 copy](https://user-images.githubusercontent.com/40273816/125182095-81698700-e1e1-11eb-886a-55940f581a7b.png) ![shelterDamaged_4 copy](https://user-images.githubusercontent.com/40273816/125182096-82021d80-e1e1-11eb-8bf5-9bd72b38f9f0.png) ![shelterDamaged_5 copy](https://user-images.githubusercontent.com/40273816/125182097-82021d80-e1e1-11eb-8381-c67cb6f64889.png) ![shelterDamaged_6 copy](https://user-images.githubusercontent.com/40273816/125182098-829ab400-e1e1-11eb-90a8-d5393fa0760f.png) ![shelterDamaged_7 copy](https://user-images.githubusercontent.com/40273816/125182099-829ab400-e1e1-11eb-81fb-a643029dcc3f.png) ![shelterDamaged_8 copy](https://user-images.githubusercontent.com/40273816/125182100-83334a80-e1e1-11eb-9822-46fd3671beee.png) ![shelterDamaged_9 copy](https://user-images.githubusercontent.com/40273816/125182101-83334a80-e1e1-11eb-9762-3b776a303192.png)

In the original game, when projectiles — from the player or the invaders — collide with a shelter, they destroy a portion of it on the collision point.

<img alt="Shelter destruction" src="https://user-images.githubusercontent.com/40273816/125180942-5a598800-e1d6-11eb-8b91-6eeba6dec277.gif">

## Destruction
The damage to the shelter seems to be based on the sprite of the projectile explosion. The current sprites of the player's and invader's projectile explosions are below. I couldn't find any good sprites, so I made these using YouTube videos as reference. All three types of enemy projectiles appear to use the same explosion sprite.

<img alt="Player's projectile explosion" src="https://user-images.githubusercontent.com/40273816/125181457-4bc19f80-e1db-11eb-80c9-f7b9d79ed87f.png"> <img alt="Invader's projectile explosion" src="https://user-images.githubusercontent.com/40273816/125181456-4b290900-e1db-11eb-91ca-a4467860b516.png">

The damage an invader does to a shelter is a little different. It doesn't use the sprite of the invader, but rather an invisible box that is slightly wider than the invader.

![enemyDestroyingShelter](https://user-images.githubusercontent.com/40273816/125182631-09519000-e1e6-11eb-82a3-eeb91762f592.gif)

## Collisions
The collision detection also seems to be based on the actual pixels, rather than on static collision boxes, which is why “wiggly” projectile are able to collide and explode near the bottom of a shelter. 

On the first frame that a projectile collides with a shelter, it does damage equals to the intersection between the sprites. On the next frame, the projectile continues to move further down and then, on the same frame, it explodes and damages the shelter using the sprite of the explosion. The same thing applies for projectile from the player.

A similar mechanic seems to apply to the collision and destruction of the green line representing the player's base at the bottom of the screen. Although, in that case, the projectiles don't appear to further penetrate the base, and explode immediately on collision.

## Tasks
- [ ] Implement damage to the shelters based on the sprites of the projectiles and their explosions.
- [ ] Same thing for the player's base.
- [ ] Implement damage to the shelters based on the invader's position.
- [ ] Implement pixel-based collision detection (or something that achieves the same result) for projectiles hitting a shelter.
